<a href="https://colab.research.google.com/github/AnubhaJarwal/HDSC-Introduction-to-Python-for-machine-learning/blob/master/Hamoye.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("HamoyeData.csv")

In [8]:
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [9]:
df.head(20)

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
5,4,Algeria,2903,Vegetal Products,664,Food supply (kcal/capita/day),kcal/capita/day,2932.00,2958.00,2941.00,2921.00,2932.00
6,4,Algeria,2903,Vegetal Products,674,Protein supply quantity (g/capita/day),g/capita/day,67.14,67.38,67.37,66.11,67.10
7,4,Algeria,2903,Vegetal Products,684,Fat supply quantity (g/capita/day),g/capita/day,53.84,54.72,52.04,55.59,54.57
8,4,Algeria,2941,Animal Products,664,Food supply (kcal/capita/day),kcal/capita/day,444.00,421.00,431.00,421.00,390.00
9,4,Algeria,2941,Animal Products,674,Protein supply quantity (g/capita/day),g/capita/day,27.76,26.97,27.35,26.71,24.73
10,4,Algeria,2941,Animal Products,684,Fat supply quantity (g/capita/day),g/capita/day,26.22,24.64,25.37,24.60,22.71
11,4,Algeria,2905,Cereals - Excluding Beer,5511,Production,1000 tonnes,3436.00,3761.00,3445.00,3478.00,6065.00
12,4,Algeria,2905,Cereals - Excluding Beer,5611,Import Quantity,1000 tonnes,12604.00,13983.00,13523.00,13039.00,13182.00
13,4,Algeria,2905,Cereals - Excluding Beer,5072,Stock Variation,1000 tonnes,684.00,1663.00,905.00,705.00,2226.00
14,4,Algeria,2905,Cereals - Excluding Beer,5911,Export Quantity,1000 tonnes,3.00,7.00,7.00,10.00,17.00
15,4,Algeria,2905,Cereals - Excluding Beer,5301,Domestic supply quantity,1000 tonnes,15353.00,16075.00,16056.00,15803.00,17004.00
16,4,Algeria,2905,Cereals - Excluding Beer,5521,Feed,1000 tonnes,4725.00,5070.00,4838.00,4667.00,5266.00
17,4,Algeria,2905,Cereals - Excluding Beer,5527,Seed,1000 tonnes,177.00,189.00,197.00,202.00,278.00
18,4,Algeria,2905,Cereals - Excluding Beer,5123,Losses,1000 tonnes,1084.00,1203.00,1148.00,1121.00,1253.00
19,4,Algeria,2905,Cereals - Excluding Beer,5131,Processing,1000 tonnes,35.00,38.00,37.00,33.00,44.00

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60943 entries, 0 to 60942
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Area Code     60943 non-null  int64
 1   Area          60943 non-null  object
 2   Item Code     60943 non-null  int64
 3   Item          60943 non-null  object
 4   Element Code  60943 non-null  int64
 5   Element       60943 non-null  object
 6   Unit          60943 non-null  object
 7   Y2014         59354 non-null  float64
 8   Y2015         59395 non-null  float64
 9   Y2016         59408 non-null  float64
 10  Y2017         59437 non-null  float64
 11  Y2018         59507 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 5.6+ MB

In [11]:
df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [12]:
selected_columns = df[['Y2017', 'Area']]
grouped_data = selected_columns.groupby('Area')['Y2017'].sum()
sorted_grouped = grouped_data.sort_values().reset_index()
seventh_lowest= sorted_grouped.iloc[6]['Area']
seventh_lowest

'Guinea-Bissau'

In [13]:
missing_count = df['Y2014'].isnull().sum()
total_count = len(df['Y2014'])
percentage_missing = (missing_count / total_count) * 100
print(missing_count , percentage_missing)

1589 2.6073544131401474

In [14]:
group_data = df.groupby('Element')['Y2017'].sum()
group_data.get('Processing', 0)

292836.0

In [15]:
corr = df[['Element Code', 'Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018']].corr()
least_correlated = correlations['Element Code'].idxmin()
least_correlated

'Y2016'

In [16]:
protein_supply = df[(df['Area'] == 'Madagascar') & (df['Element'] == 'Protein supply quantity (g/capita/day)')]
grouped_data = protein_supply.groupby(['Element', 'Area'])['Y2015'].sum()
protein_supply_2015 = grouped_data.get(('Protein supply quantity (g/capita/day)', 'Madagascar'), 0)
print(protein_supply_2015)

173.05

In [17]:
group = df.groupby('Item')['Y2015', 'Y2018'].sum().reset_index()
wine2015 = group[group['Item'] == 'Wine']['Y2015'].values[0]
wine2018 = group[group['Item'] == 'Wine']['Y2018'].values[0]
print(wine2015 , wine2018)

4251.81 4039.32

<ipython-input-17-ec586f271286>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  group = df.groupby('Item')['Y2015', 'Y2018'].sum().reset_index()

In [19]:
area_unique = df["Area"].unique()
len(area_unique)

49

In [20]:
selected_columns = df[['Y2017', 'Area']]
grouped_data = selected_columns.groupby('Area')['Y2017'].sum()
highest_sum = grouped_data.idxmax()
print(highest_sum)

Nigeria

In [22]:
year_columns = ['Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018']
df['Total_Variation'] = df[year_columns].sum(axis=1)
year = df[year_columns].sum().idxmax()
print(year)

Y2018

In [23]:
stock_variation_df = df[df['Element'] == 'Stock Variation']
grouped_data = stock_variation_df[['Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018']].sum()
year= grouped_data.idxmax()
print(year)

Y2014